<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

use \Calctool\Models\SubGroup;
use \Calctool\Models\Supplier;
use \Calctool\Models\UserType;
use \Calctool\Models\Province;
use \Calctool\Models\Country;
use \Calctool\Models\ProjectType;
use \Calctool\Models\Part;
use \Calctool\Models\PartType;
use \Calctool\Models\Detail;
use \Calctool\Models\ContactFunction;
use \Calctool\Models\RelationType;
use \Calctool\Models\RelationKind;
use \Calctool\Models\WholesaleType;
use \Calctool\Models\Valid;
use \Calctool\Models\DeliverTime;
use \Calctool\Models\Tax;
use \Calctool\Models\TimesheetKind;
use \Calctool\Models\PurchaseKind;
use \Calctool\Models\SysMessage;

/*
 * Static Models Only
 * Test are performed on other seeds
 */
class StaticSeeder extends Seeder {

	public function run()
	{

		DB::table('sub_group')->delete();
		DB::table('supplier')->delete();
		DB::table('tax')->delete();
		DB::table('deliver_time')->delete();
		DB::table('valid')->delete();
		DB::table('relation_kind')->delete();
		DB::table('relation_type')->delete();
		DB::table('contact_function')->delete();
		DB::table('part_type')->delete();
		DB::table('part')->delete();
		DB::table('project_type')->delete();
		DB::table('country')->delete();
		DB::table('province')->delete();
		DB::table('user_type')->delete();
		$this->command->info('Tables deleted');

		SubGroup::create(array('reference_code'=>'16-64-1','group_type'=>'aardkleuren'));
		SubGroup::create(array('reference_code'=>'14-48-8','group_type'=>'accessoires (deel1)'));
		SubGroup::create(array('reference_code'=>'13-35-2','group_type'=>'accessoires (deel 2)'));
		SubGroup::create(array('reference_code'=>'14-40-5','group_type'=>'afbouwersgereedschap'));
		SubGroup::create(array('reference_code'=>'14-46-18','group_type'=>'afdekken'));
		SubGroup::create(array('reference_code'=>'14-42-4','group_type'=>'afplakband/tapes'));
		SubGroup::create(array('reference_code'=>'12-21-50','group_type'=>'afvoeren en toebehoren'));
		SubGroup::create(array('reference_code'=>'16-60-1','group_type'=>'afwerkverf'));
		SubGroup::create(array('reference_code'=>'16-65-1','group_type'=>'afwerkverven'));
		SubGroup::create(array('reference_code'=>'14-48-5','group_type'=>'akkumachines'));
		SubGroup::create(array('reference_code'=>'10-10-6','group_type'=>'aluminium programma'));
		SubGroup::create(array('reference_code'=>'15-54-2','group_type'=>'aluminiumprofielen'));
		SubGroup::create(array('reference_code'=>'15-54-3','group_type'=>'ankerprogramma'));
		SubGroup::create(array('reference_code'=>'14-46-17','group_type'=>'automotive'));
		SubGroup::create(array('reference_code'=>'12-25-8','group_type'=>'badkuipen'));
		SubGroup::create(array('reference_code'=>'13-33-3','group_type'=>'batterijen'));
		SubGroup::create(array('reference_code'=>'14-55-13','group_type'=>'beitels'));
		SubGroup::create(array('reference_code'=>'16-61-1','group_type'=>'beitsen'));
		SubGroup::create(array('reference_code'=>'16-61-99','group_type'=>'beitsen diversen'));
		SubGroup::create(array('reference_code'=>'13-31-21','group_type'=>'berker'));
		SubGroup::create(array('reference_code'=>'10-6-1','group_type'=>'beton dakpannen'));
		SubGroup::create(array('reference_code'=>'10-11-3','group_type'=>'beton ijzer'));
		SubGroup::create(array('reference_code'=>'10-3-1','group_type'=>'betontegels'));
		SubGroup::create(array('reference_code'=>'13-32-6','group_type'=>'beveiliging'));
		SubGroup::create(array('reference_code'=>'12-21-18','group_type'=>'bevest. mat. rk-buis'));
		SubGroup::create(array('reference_code'=>'13-31-14','group_type'=>'bevestigingsmat./buis'));
		SubGroup::create(array('reference_code'=>'16-63-50','group_type'=>'bison professional lijmen'));
		SubGroup::create(array('reference_code'=>'11-17-1','group_type'=>'boarddeuren'));
		SubGroup::create(array('reference_code'=>'14-48-4','group_type'=>'boorhamers/hakhamers'));
		SubGroup::create(array('reference_code'=>'14-48-1','group_type'=>'boormachines'));
		SubGroup::create(array('reference_code'=>'14-49-2','group_type'=>'boren'));
		SubGroup::create(array('reference_code'=>'14-49-12','group_type'=>'boren diversen'));
		SubGroup::create(array('reference_code'=>'10-13-5','group_type'=>'bouwmaat'));
		SubGroup::create(array('reference_code'=>'16-63-3','group_type'=>'bouwmaat kitten'));
		SubGroup::create(array('reference_code'=>'10-11-5','group_type'=>'bouwprofielen'));
		SubGroup::create(array('reference_code'=>'11-17-6','group_type'=>'branddeuren'));
		SubGroup::create(array('reference_code'=>'13-31-12','group_type'=>'buig- en trekveren'));
		SubGroup::create(array('reference_code'=>'12-21-35','group_type'=>'buis bevestigingsbeugels'));
		SubGroup::create(array('reference_code'=>'12-23-8','group_type'=>'buisrozetten en bevest.'));
		SubGroup::create(array('reference_code'=>'13-32-7','group_type'=>'buitenverlichting'));
		SubGroup::create(array('reference_code'=>'13-32-2','group_type'=>'bulleyes/looplampen'));
		SubGroup::create(array('reference_code'=>'13-31-4','group_type'=>'busch & jager'));
		SubGroup::create(array('reference_code'=>'14-46-7','group_type'=>'butaan/propaangereedschap'));
		SubGroup::create(array('reference_code'=>'12-23-4','group_type'=>'c.v. instal.mat + toebeh.'));
		SubGroup::create(array('reference_code'=>'12-23-2','group_type'=>'c.v. ketels'));
		SubGroup::create(array('reference_code'=>'10-1-1','group_type'=>'cement'));
		SubGroup::create(array('reference_code'=>'14-49-4','group_type'=>'cirkelzaagbladen'));
		SubGroup::create(array('reference_code'=>'13-31-17','group_type'=>'coax - telefoon aansl.'));
		SubGroup::create(array('reference_code'=>'12-24-22','group_type'=>'comfort'));
		SubGroup::create(array('reference_code'=>'12-23-15','group_type'=>'compact radiatoren'));
		SubGroup::create(array('reference_code'=>'12-21-40','group_type'=>'cv fittingen'));
		SubGroup::create(array('reference_code'=>'10-6-99','group_type'=>'dakbedekking diversen'));
		SubGroup::create(array('reference_code'=>'10-5-16','group_type'=>'dakplaten'));
		SubGroup::create(array('reference_code'=>'10-6-4','group_type'=>'dakramen'));
		SubGroup::create(array('reference_code'=>'10-6-7','group_type'=>'dakreparatie'));
		SubGroup::create(array('reference_code'=>'10-6-3','group_type'=>'dakrollen'));
		SubGroup::create(array('reference_code'=>'16-62-99','group_type'=>'decoratie diversen'));
		SubGroup::create(array('reference_code'=>'14-49-3','group_type'=>'decoupeerzaagbladen'));
		SubGroup::create(array('reference_code'=>'10-11-7','group_type'=>'dekkleden'));
		SubGroup::create(array('reference_code'=>'12-23-14','group_type'=>'design radiatoren'));
		SubGroup::create(array('reference_code'=>'15-51-52','group_type'=>'deurbeslag'));
		SubGroup::create(array('reference_code'=>'11-17-99','group_type'=>'deuren diversen'));
		SubGroup::create(array('reference_code'=>'14-48-7','group_type'=>'div. elek. gereedschap'));
		SubGroup::create(array('reference_code'=>'15-51-57','group_type'=>'div. garnituren/scharn.'));
		SubGroup::create(array('reference_code'=>'15-51-55','group_type'=>'div.hang- en sluitwerk'));
		SubGroup::create(array('reference_code'=>'10-11-99','group_type'=>'diversen (deel 1)'));
		SubGroup::create(array('reference_code'=>'15-52-99','group_type'=>'diversen (deel 2)'));
		SubGroup::create(array('reference_code'=>'14-46-14','group_type'=>'diversen (deel 3)'));
		SubGroup::create(array('reference_code'=>'13-33-99','group_type'=>'diversen (deel 4)'));
		SubGroup::create(array('reference_code'=>'11-11-99','group_type'=>'diversen zachthout'));
		SubGroup::create(array('reference_code'=>'13-31-23','group_type'=>'domotica'));
		SubGroup::create(array('reference_code'=>'14-46-3','group_type'=>'dompelpompen'));
		SubGroup::create(array('reference_code'=>'12-24-7','group_type'=>'douche slangen'));
		SubGroup::create(array('reference_code'=>'12-25-9','group_type'=>'douchebakken'));
		SubGroup::create(array('reference_code'=>'12-24-8','group_type'=>'douchewand+hoekinstap'));
		SubGroup::create(array('reference_code'=>'13-31-13','group_type'=>'draad/kabel'));
		SubGroup::create(array('reference_code'=>'14-55-16','group_type'=>'drevels/deuvels'));
		SubGroup::create(array('reference_code'=>'10-5-7','group_type'=>'dubbele beglazing'));
		SubGroup::create(array('reference_code'=>'12-25-5','group_type'=>'duobloks'));
		SubGroup::create(array('reference_code'=>'10-13-1','group_type'=>'eurocol'));
		SubGroup::create(array('reference_code'=>'12-23-7','group_type'=>'expansievaten en toebeh.'));
		SubGroup::create(array('reference_code'=>'14-48-9','group_type'=>'fein macines'));
		SubGroup::create(array('reference_code'=>'14-49-14','group_type'=>'fein toebehoren'));
		SubGroup::create(array('reference_code'=>'10-4-4','group_type'=>'fermacell'));
		SubGroup::create(array('reference_code'=>'15-52-51','group_type'=>'fis profi bouten & schr.'));
		SubGroup::create(array('reference_code'=>'15-52-52','group_type'=>'fis profi draadnagels'));
		SubGroup::create(array('reference_code'=>'12-21-36','group_type'=>'flexibele beschermbuis'));
		SubGroup::create(array('reference_code'=>'12-21-42','group_type'=>'flexibele slangen'));
		SubGroup::create(array('reference_code'=>'10-5-8','group_type'=>'folieen'));
		SubGroup::create(array('reference_code'=>'12-25-4','group_type'=>'fonteinen'));
		SubGroup::create(array('reference_code'=>'14-49-10','group_type'=>'frezen'));
		SubGroup::create(array('reference_code'=>'12-23-9','group_type'=>'gas artikelen sanivesk'));
		SubGroup::create(array('reference_code'=>'10-2-3','group_type'=>'gasbet0n -en gipsblokken'));
		SubGroup::create(array('reference_code'=>'12-21-20','group_type'=>'gaskranen en -slangen'));
		SubGroup::create(array('reference_code'=>'12-23-1','group_type'=>'geisers en boilers'));
		SubGroup::create(array('reference_code'=>'11-16-1','group_type'=>'gemelamineerd spaanplaat'));
		SubGroup::create(array('reference_code'=>'11-11-4','group_type'=>'gemodificeerd hout'));
		SubGroup::create(array('reference_code'=>'11-12-1','group_type'=>'geschaafd'));
		SubGroup::create(array('reference_code'=>'10-1-4','group_type'=>'gips + kalk'));
		SubGroup::create(array('reference_code'=>'10-4-1','group_type'=>'gipsplaat'));
		SubGroup::create(array('reference_code'=>'13-31-24','group_type'=>'gira'));
		SubGroup::create(array('reference_code'=>'11-14-1','group_type'=>'glaslatten'));
		SubGroup::create(array('reference_code'=>'10-5-1','group_type'=>'glaswolrollen/platen'));
		SubGroup::create(array('reference_code'=>'10-11-9','group_type'=>'glazen bouwstenen'));
		SubGroup::create(array('reference_code'=>'12-24-5','group_type'=>'glijstangsets'));
		SubGroup::create(array('reference_code'=>'10-6-6','group_type'=>'golfplaten'));
		SubGroup::create(array('reference_code'=>'15-54-8','group_type'=>'gordijnrails'));
		SubGroup::create(array('reference_code'=>'15-51-51','group_type'=>'grendel/sluiting/schuiven'));
		SubGroup::create(array('reference_code'=>'10-3-2','group_type'=>'grindtegels'));
		SubGroup::create(array('reference_code'=>'13-31-11','group_type'=>'groepenkasten'));
		SubGroup::create(array('reference_code'=>'12-26-3','group_type'=>'grohe kranen eurodisc'));
		SubGroup::create(array('reference_code'=>'12-26-17','group_type'=>'grohe kranen eurosmart'));
		SubGroup::create(array('reference_code'=>'12-26-16','group_type'=>'grohe kranen thermostaat'));
		SubGroup::create(array('reference_code'=>'12-26-19','group_type'=>'grohe supra'));
		SubGroup::create(array('reference_code'=>'13-32-3','group_type'=>'halogeenlampen'));
		SubGroup::create(array('reference_code'=>'13-34-1','group_type'=>'halogeenspots'));
		SubGroup::create(array('reference_code'=>'14-55-10','group_type'=>'hamers'));
		SubGroup::create(array('reference_code'=>'12-24-6','group_type'=>'handdouches'));
		SubGroup::create(array('reference_code'=>'14-55-21','group_type'=>'handgereedschap diversen'));
		SubGroup::create(array('reference_code'=>'11-15-3','group_type'=>'hardboard'));
		SubGroup::create(array('reference_code'=>'14-48-6','group_type'=>'hechtapparaten'));
		SubGroup::create(array('reference_code'=>'12-22-3','group_type'=>'hemelwaterafv.bakken+goot'));
		SubGroup::create(array('reference_code'=>'12-22-4','group_type'=>'hemelwaterafv.hulpstukken'));
		SubGroup::create(array('reference_code'=>'15-54-9','group_type'=>'horren'));
		SubGroup::create(array('reference_code'=>'15-54-4','group_type'=>'hout- en bouwankers'));
		SubGroup::create(array('reference_code'=>'15-52-2','group_type'=>'houtschroeven vk en pk'));
		SubGroup::create(array('reference_code'=>'18-81-3','group_type'=>'inbouwkookplaten'));
		SubGroup::create(array('reference_code'=>'18-81-5','group_type'=>'inbouwovens'));
		SubGroup::create(array('reference_code'=>'13-31-9','group_type'=>'installatie materiaal'));
		SubGroup::create(array('reference_code'=>'13-31-99','group_type'=>'installatiemat. diversen'));
		SubGroup::create(array('reference_code'=>'13-31-10','group_type'=>'isolatie aard/zekering'));
		SubGroup::create(array('reference_code'=>'10-5-99','group_type'=>'isolatie diversen'));
		SubGroup::create(array('reference_code'=>'13-31-20','group_type'=>'jung'));
		SubGroup::create(array('reference_code'=>'13-31-16','group_type'=>'k25+k40 systeem'));
		SubGroup::create(array('reference_code'=>'14-60-1','group_type'=>'keetconcept'));
		SubGroup::create(array('reference_code'=>'14-61-1','group_type'=>'keetconcept 0,06'));
		SubGroup::create(array('reference_code'=>'10-6-2','group_type'=>'keramische pannen'));
		SubGroup::create(array('reference_code'=>'15-54-12','group_type'=>'ketting'));
		SubGroup::create(array('reference_code'=>'16-63-5','group_type'=>'kitten'));
		SubGroup::create(array('reference_code'=>'14-46-12','group_type'=>'kleding'));
		SubGroup::create(array('reference_code'=>'16-65-4','group_type'=>'kleurenwaaiers'));
		SubGroup::create(array('reference_code'=>'12-25-6','group_type'=>'klosetpotten'));
		SubGroup::create(array('reference_code'=>'12-26-18','group_type'=>'kludi kranen'));
		SubGroup::create(array('reference_code'=>'12-21-31','group_type'=>'knelfittingen'));
		SubGroup::create(array('reference_code'=>'12-21-38','group_type'=>'knelstopkraan sanivesk'));
		SubGroup::create(array('reference_code'=>'15-51-56','group_type'=>'knoppen/grepen/haken'));
		SubGroup::create(array('reference_code'=>'18-81-7','group_type'=>'koelautomaten'));
		SubGroup::create(array('reference_code'=>'13-31-15','group_type'=>'kontakt-materiaal'));
		SubGroup::create(array('reference_code'=>'11-14-3','group_type'=>'kop-,hoek- en hollatten'));
		SubGroup::create(array('reference_code'=>'11-18-3','group_type'=>'kozijn- en raamprofielen'));
		SubGroup::create(array('reference_code'=>'12-21-46','group_type'=>'kraan toebehoren'));
		SubGroup::create(array('reference_code'=>'12-26-4','group_type'=>'kraankoppelingen'));
		SubGroup::create(array('reference_code'=>'18-82-2','group_type'=>'kunststof'));
		SubGroup::create(array('reference_code'=>'15-54-1','group_type'=>'kunststof profielen/strip'));
		SubGroup::create(array('reference_code'=>'11-13-6','group_type'=>'kunststof schroten'));
		SubGroup::create(array('reference_code'=>'11-15-7','group_type'=>'kunststofplaten'));
		SubGroup::create(array('reference_code'=>'14-42-1','group_type'=>'kwasten'));
		SubGroup::create(array('reference_code'=>'14-50-1','group_type'=>'ladders en trappen'));
		SubGroup::create(array('reference_code'=>'16-61-2','group_type'=>'lakken'));
		SubGroup::create(array('reference_code'=>'11-20-2','group_type'=>'laminaat'));
		SubGroup::create(array('reference_code'=>'13-32-5','group_type'=>'lampen'));
		SubGroup::create(array('reference_code'=>'13-31-7','group_type'=>'lamphouders'));
		SubGroup::create(array('reference_code'=>'10-11-1','group_type'=>'lateien'));
		SubGroup::create(array('reference_code'=>'16-60-2','group_type'=>'latex/muurverven'));
		SubGroup::create(array('reference_code'=>'14-46-8','group_type'=>'lederen gereedschaphouder'));
		SubGroup::create(array('reference_code'=>'10-5-5','group_type'=>'leiding isolatie'));
		SubGroup::create(array('reference_code'=>'10-11-2','group_type'=>'lewisplaten'));
		SubGroup::create(array('reference_code'=>'10-6-5','group_type'=>'lichtkoepels'));
		SubGroup::create(array('reference_code'=>'16-63-1','group_type'=>'lijmen div.'));
		SubGroup::create(array('reference_code'=>'11-14-7','group_type'=>'lijstwerk diversen'));
		SubGroup::create(array('reference_code'=>'12-24-25','group_type'=>'linido'));
		SubGroup::create(array('reference_code'=>'15-50-3','group_type'=>'luxe sierbeslag'));
		SubGroup::create(array('reference_code'=>'18-81-9','group_type'=>'magnetrons'));
		SubGroup::create(array('reference_code'=>'12-21-39','group_type'=>'malleabele fittingen'));
		SubGroup::create(array('reference_code'=>'11-16-2','group_type'=>'massief vuren/grenen'));
		SubGroup::create(array('reference_code'=>'14-55-19','group_type'=>'meet/aftekengereedschap'));
		SubGroup::create(array('reference_code'=>'11-17-3','group_type'=>'meranti deuren'));
		SubGroup::create(array('reference_code'=>'11-17-4','group_type'=>'merbau deuren'));
		SubGroup::create(array('reference_code'=>'12-24-13','group_type'=>'metaal eclips chroom'));
		SubGroup::create(array('reference_code'=>'14-40-99','group_type'=>'metsel&bouwgereeds. div.'));
		SubGroup::create(array('reference_code'=>'14-40-4','group_type'=>'metselaarsgereedschap'));
		SubGroup::create(array('reference_code'=>'10-2-1','group_type'=>'metselbakstenen'));
		SubGroup::create(array('reference_code'=>'10-9-10','group_type'=>'metzger'));
		SubGroup::create(array('reference_code'=>'11-16-99','group_type'=>'meubelpanelen diversen'));
		SubGroup::create(array('reference_code'=>'14-46-5','group_type'=>'mortelkuipen/betonmolens'));
		SubGroup::create(array('reference_code'=>'10-1-3','group_type'=>'mortels'));
		SubGroup::create(array('reference_code'=>'10-7-7','group_type'=>'mosa wandtegels'));
		SubGroup::create(array('reference_code'=>'11-15-1','group_type'=>'multiplex'));
		SubGroup::create(array('reference_code'=>'12-24-23','group_type'=>'murcia'));
		SubGroup::create(array('reference_code'=>'15-52-19','group_type'=>'nagels diversen'));
		SubGroup::create(array('reference_code'=>'10-2-5','group_type'=>'natuursteen'));
		SubGroup::create(array('reference_code'=>'14-49-8','group_type'=>'nieten'));
		SubGroup::create(array('reference_code'=>'13-31-1','group_type'=>'opbouw materiaal'));
		SubGroup::create(array('reference_code'=>'10-11-6','group_type'=>'open haarden'));
		SubGroup::create(array('reference_code'=>'10-3-4','group_type'=>'opsluitbanden'));
		SubGroup::create(array('reference_code'=>'12-25-10','group_type'=>'overig plaatstaal sanit.'));
		SubGroup::create(array('reference_code'=>'12-26-8','group_type'=>'overige toebehoren kranen'));
		SubGroup::create(array('reference_code'=>'11-14-6','group_type'=>'overzetplinten e.d.'));
		SubGroup::create(array('reference_code'=>'12-22-99','group_type'=>'p.v.c. diversen'));
		SubGroup::create(array('reference_code'=>'13-35-1','group_type'=>'panelen'));
		SubGroup::create(array('reference_code'=>'11-20-1','group_type'=>'parkethout'));
		SubGroup::create(array('reference_code'=>'13-31-22','group_type'=>'peha'));
		SubGroup::create(array('reference_code'=>'14-49-13','group_type'=>'perflex'));
		SubGroup::create(array('reference_code'=>'13-31-3','group_type'=>'perilex'));
		SubGroup::create(array('reference_code'=>'14-46-9','group_type'=>'persoonlijke bescherming'));
		SubGroup::create(array('reference_code'=>'12-21-56','group_type'=>'pexfit'));
		SubGroup::create(array('reference_code'=>'10-4-99','group_type'=>'plaatmat. bouw diversen'));
		SubGroup::create(array('reference_code'=>'11-21-2','group_type'=>'plafondplaten'));
		SubGroup::create(array('reference_code'=>'10-11-10','group_type'=>'plafondsystemen'));
		SubGroup::create(array('reference_code'=>'13-34-3','group_type'=>'plafonniers'));
		SubGroup::create(array('reference_code'=>'12-25-3','group_type'=>'planchets'));
		SubGroup::create(array('reference_code'=>'15-54-5','group_type'=>'plankdragers'));
		SubGroup::create(array('reference_code'=>'10-10-5','group_type'=>'platte buis systeem'));
		SubGroup::create(array('reference_code'=>'11-12-99','group_type'=>'plinten'));
		SubGroup::create(array('reference_code'=>'15-52-25','group_type'=>'pluggen'));
		SubGroup::create(array('reference_code'=>'10-6-9','group_type'=>'polycarb./plexiglas'));
		SubGroup::create(array('reference_code'=>'10-5-3','group_type'=>'polystyreen platen'));
		SubGroup::create(array('reference_code'=>'12-21-32','group_type'=>'push-in steekfittingen'));
		SubGroup::create(array('reference_code'=>'10-8-2','group_type'=>'raamdorpelstenen'));
		SubGroup::create(array('reference_code'=>'15-51-53','group_type'=>'raamsluitwerk'));
		SubGroup::create(array('reference_code'=>'12-23-6','group_type'=>'radiator en cv toebehoren'));
		SubGroup::create(array('reference_code'=>'10-9-6','group_type'=>'reiniging + onderhoud'));
		SubGroup::create(array('reference_code'=>'16-60-4','group_type'=>'reiniging en verdunning'));
		SubGroup::create(array('reference_code'=>'12-21-47','group_type'=>'reservoir toebehoren'));
		SubGroup::create(array('reference_code'=>'12-25-7','group_type'=>'reservoirs'));
		SubGroup::create(array('reference_code'=>'12-21-49','group_type'=>'ringen en schijfjes'));
		SubGroup::create(array('reference_code'=>'15-52-21','group_type'=>'ringen,draadstangen'));
		SubGroup::create(array('reference_code'=>'12-22-1','group_type'=>'riolering buizen'));
		SubGroup::create(array('reference_code'=>'12-22-2','group_type'=>'riolering hulpstukken'));
		SubGroup::create(array('reference_code'=>'14-42-2','group_type'=>'rollers'));
		SubGroup::create(array('reference_code'=>'11-14-4','group_type'=>'rond/halfrond/kwartrond'));
		SubGroup::create(array('reference_code'=>'12-21-9','group_type'=>'rood koperen buis'));
		SubGroup::create(array('reference_code'=>'12-21-34','group_type'=>'roodkoperen fittingen'));
		SubGroup::create(array('reference_code'=>'10-10-7','group_type'=>'rookgas afvoer'));
		SubGroup::create(array('reference_code'=>'10-10-2','group_type'=>'rookgasdoorvoer'));
		SubGroup::create(array('reference_code'=>'15-54-50','group_type'=>'roosters'));
		SubGroup::create(array('reference_code'=>'14-41-1','group_type'=>'rothenberger'));
		SubGroup::create(array('reference_code'=>'12-21-45','group_type'=>'rozetten en verlengst.chr'));
		SubGroup::create(array('reference_code'=>'18-82-1','group_type'=>'rvs'));
		SubGroup::create(array('reference_code'=>'12-24-99','group_type'=>'sanitair accessoires div.'));
		SubGroup::create(array('reference_code'=>'12-21-43','group_type'=>'sanitair bevest.materiaal'));
		SubGroup::create(array('reference_code'=>'15-51-54','group_type'=>'scharnieren'));
		SubGroup::create(array('reference_code'=>'10-4-2','group_type'=>'scheidingswand'));
		SubGroup::create(array('reference_code'=>'13-33-2','group_type'=>'schel/travo/buitendeurdr.'));
		SubGroup::create(array('reference_code'=>'14-42-3','group_type'=>'schildersgereedschappen'));
		SubGroup::create(array('reference_code'=>'10-13-2','group_type'=>'schonox'));
		SubGroup::create(array('reference_code'=>'14-50-3','group_type'=>'schragen en bokken'));
		SubGroup::create(array('reference_code'=>'14-49-7','group_type'=>'schroefbits'));
		SubGroup::create(array('reference_code'=>'15-52-10','group_type'=>'schroeven diversen'));
		SubGroup::create(array('reference_code'=>'14-55-14','group_type'=>'schroevendraaiers'));
		SubGroup::create(array('reference_code'=>'11-13-2','group_type'=>'schroten hardhout'));
		SubGroup::create(array('reference_code'=>'11-13-1','group_type'=>'schroten zachthout'));
		SubGroup::create(array('reference_code'=>'11-17-21','group_type'=>'schuifdeursystemen'));
		SubGroup::create(array('reference_code'=>'14-49-6','group_type'=>'schuurpapier'));
		SubGroup::create(array('reference_code'=>'16-65-2','group_type'=>'sierpleisters (deel 2)'));
		SubGroup::create(array('reference_code'=>'16-62-1','group_type'=>'sierpleisters (deel 1)'));
		SubGroup::create(array('reference_code'=>'16-66-5','group_type'=>'sikkens'));
		SubGroup::create(array('reference_code'=>'14-46-4','group_type'=>'slangen en toebehoren'));
		SubGroup::create(array('reference_code'=>'14-48-3','group_type'=>'slijpmachines'));
		SubGroup::create(array('reference_code'=>'14-49-5','group_type'=>'slijpschijven,borstels'));
		SubGroup::create(array('reference_code'=>'15-51-50','group_type'=>'sloten'));
		SubGroup::create(array('reference_code'=>'12-21-33','group_type'=>'soldeer/draadfittingen'));
		SubGroup::create(array('reference_code'=>'12-21-30','group_type'=>'soldeerfittingen'));
		SubGroup::create(array('reference_code'=>'14-55-18','group_type'=>'soldeergereedschap'));
		SubGroup::create(array('reference_code'=>'11-15-2','group_type'=>'spaanplaat'));
		SubGroup::create(array('reference_code'=>'15-52-5','group_type'=>'spaanplaatschroeven'));
		SubGroup::create(array('reference_code'=>'12-24-4','group_type'=>'spiegels'));
		SubGroup::create(array('reference_code'=>'10-10-3','group_type'=>'spirovent buizen & hulpst'));
		SubGroup::create(array('reference_code'=>'18-82-3','group_type'=>'spoelbakken'));
		SubGroup::create(array('reference_code'=>'11-18-1','group_type'=>'standaard kozijnen hout'));
		SubGroup::create(array('reference_code'=>'11-18-2','group_type'=>'standaard kozijnen metaal'));
		SubGroup::create(array('reference_code'=>'14-55-20','group_type'=>'stanley messen'));
		SubGroup::create(array('reference_code'=>'10-5-2','group_type'=>'steenwolrollen/platen'));
		SubGroup::create(array('reference_code'=>'14-50-4','group_type'=>'steigers en toebehoren'));
		SubGroup::create(array('reference_code'=>'13-31-8','group_type'=>'stekker/snoerschakelaar'));
		SubGroup::create(array('reference_code'=>'10-11-4','group_type'=>'stelblokjes,afstandhouder'));
		SubGroup::create(array('reference_code'=>'11-17-5','group_type'=>'stijldeuren /lbp deuren'));
		SubGroup::create(array('reference_code'=>'14-46-2','group_type'=>'stofzuigers'));
		SubGroup::create(array('reference_code'=>'12-21-37','group_type'=>'stopkranen'));
		SubGroup::create(array('reference_code'=>'14-40-1','group_type'=>'stucadoorsgereedschap'));
		SubGroup::create(array('reference_code'=>'15-54-16','group_type'=>'stukadoorsprofielen'));
		SubGroup::create(array('reference_code'=>'10-5-4','group_type'=>'styrofoam platen'));
		SubGroup::create(array('reference_code'=>'13-32-4','group_type'=>'t.l.'));
		SubGroup::create(array('reference_code'=>'13-31-6','group_type'=>'tafelkontaktdoos'));
		SubGroup::create(array('reference_code'=>'14-55-17','group_type'=>'tangen'));
		SubGroup::create(array('reference_code'=>'12-21-44','group_type'=>'tapkranen en toebehoren'));
		SubGroup::create(array('reference_code'=>'14-40-2','group_type'=>'tegelzettersgereedschap'));
		SubGroup::create(array('reference_code'=>'15-54-10','group_type'=>'tochtprofielen'));
		SubGroup::create(array('reference_code'=>'14-49-11','group_type'=>'toeb.elek.gereedschap div'));
		SubGroup::create(array('reference_code'=>'12-23-3','group_type'=>'toebehoren c.v. radiators'));
		SubGroup::create(array('reference_code'=>'10-9-1','group_type'=>'toeslag- en hulpstoffen'));
		SubGroup::create(array('reference_code'=>'12-24-3','group_type'=>'toiletzittingen'));
		SubGroup::create(array('reference_code'=>'15-54-6','group_type'=>'touw'));
		SubGroup::create(array('reference_code'=>'14-46-6','group_type'=>'tuingereedschap'));
		SubGroup::create(array('reference_code'=>'11-11-6','group_type'=>'tuinhout'));
		SubGroup::create(array('reference_code'=>'12-21-41','group_type'=>'tyleenbuis en koppelingen'));
		SubGroup::create(array('reference_code'=>'10-5-11','group_type'=>'unidek dakisolatieplaat'));
		SubGroup::create(array('reference_code'=>'10-5-10','group_type'=>'unidek spouwisolatieplaat'));
		SubGroup::create(array('reference_code'=>'12-21-57','group_type'=>'uponor'));
		SubGroup::create(array('reference_code'=>'14-46-1','group_type'=>'vegers/bezems'));
		SubGroup::create(array('reference_code'=>'14-46-13','group_type'=>'veiligh.schoenen&laarzen'));
		SubGroup::create(array('reference_code'=>'12-26-15','group_type'=>'venlo kranen nimbus serie'));
		SubGroup::create(array('reference_code'=>'11-16-3','group_type'=>'vensterbanken/werkbladen'));
		SubGroup::create(array('reference_code'=>'10-10-1','group_type'=>'ventilatie dakdoorvoer'));
		SubGroup::create(array('reference_code'=>'13-33-1','group_type'=>'ventilatoren'));
		SubGroup::create(array('reference_code'=>'13-32-99','group_type'=>'verlichting diversen'));
		SubGroup::create(array('reference_code'=>'14-55-11','group_type'=>'vijlen / raspen'));
		SubGroup::create(array('reference_code'=>'11-13-3','group_type'=>'vloerdelen e.d. zachthout'));
		SubGroup::create(array('reference_code'=>'14-40-3','group_type'=>'vloerleggersgereedschap'));
		SubGroup::create(array('reference_code'=>'10-7-2','group_type'=>'vloertegels'));
		SubGroup::create(array('reference_code'=>'12-23-10','group_type'=>'vloerverwarming'));
		SubGroup::create(array('reference_code'=>'10-13-3','group_type'=>'vn-ci'));
		SubGroup::create(array('reference_code'=>'15-54-15','group_type'=>'voetroosters'));
		SubGroup::create(array('reference_code'=>'16-60-3','group_type'=>'voorbehandelingsprod.'));
		SubGroup::create(array('reference_code'=>'16-65-3','group_type'=>'voorstrijk (deel 2)'));
		SubGroup::create(array('reference_code'=>'16-62-2','group_type'=>'voorstrijk (deel 1)'));
		SubGroup::create(array('reference_code'=>'16-63-2','group_type'=>'vulmiddelen'));
		SubGroup::create(array('reference_code'=>'11-11-3','group_type'=>'vuren geschaafd'));
		SubGroup::create(array('reference_code'=>'11-17-12','group_type'=>'vuren houten deuren'));
		SubGroup::create(array('reference_code'=>'11-11-1','group_type'=>'vuren ruig'));
		SubGroup::create(array('reference_code'=>'15-54-7','group_type'=>'wandrailsysteem'));
		SubGroup::create(array('reference_code'=>'10-7-1','group_type'=>'wandtegels'));
		SubGroup::create(array('reference_code'=>'18-81-1','group_type'=>'wasemkappen'));
		SubGroup::create(array('reference_code'=>'12-21-48','group_type'=>'wasmachine toebehoren'));
		SubGroup::create(array('reference_code'=>'12-25-1','group_type'=>'wastafels'));
		SubGroup::create(array('reference_code'=>'13-31-2','group_type'=>'waterd. opb./inb. mat.'));
		SubGroup::create(array('reference_code'=>'14-48-2','group_type'=>'zaag-,schuur-schaafmach.'));
		SubGroup::create(array('reference_code'=>'14-55-12','group_type'=>'zagen'));
		SubGroup::create(array('reference_code'=>'10-1-2','group_type'=>'zand+grind'));
		SubGroup::create(array('reference_code'=>'16-63-4','group_type'=>'zwaluw lijmen en kitten'));
		SubGroup::create(array('reference_code'=>'11-13-5','group_type'=>'pvc schroten'));
		SubGroup::create(array('reference_code'=>'12-21-19','group_type'=>'knelkoppelingen'));
		SubGroup::create(array('reference_code'=>'12-21-63','group_type'=>'bonfix pers'));
		SubGroup::create(array('reference_code'=>'12-21-62','group_type'=>'quick and easy'));
		SubGroup::create(array('reference_code'=>'12-21-99','group_type'=>'sanitair divers'));
		SubGroup::create(array('reference_code'=>'12-22-5','group_type'=>'zink'));
		SubGroup::create(array('reference_code'=>'12-27-1','group_type'=>'airco'));
		SubGroup::create(array('reference_code'=>'13-36-1','group_type'=>'onbekend'));
		$this->command->info('SubGroup created');

		UserType::create(array('user_type' => 'system'));
		UserType::create(array('user_type' => 'admin'));
		UserType::create(array('user_type' => 'user'));
		UserType::create(array('user_type' => 'guest'));
		UserType::create(array('user_type' => 'tester'));
		UserType::create(array('user_type' => 'demo'));
		$this->command->info('UserType created');

		Province::create(array('province_name' => 'groningen'));
		Province::create(array('province_name' => 'friesland'));
		Province::create(array('province_name' => 'drenthe'));
		Province::create(array('province_name' => 'overijssel'));
		Province::create(array('province_name' => 'flevoland'));
		Province::create(array('province_name' => 'gelderland'));
		Province::create(array('province_name' => 'utrecht'));
		Province::create(array('province_name' => 'noord-holland'));
		Province::create(array('province_name' => 'zuid-holland'));
		Province::create(array('province_name' => 'noord-brabant'));
		Province::create(array('province_name' => 'limburg'));
		Province::create(array('province_name' => 'zeeland'));
		Province::create(array('province_name' => 'overig'));
		$this->command->info('Provance created');

		Country::create(array('country_name' => 'albanië'));
		Country::create(array('country_name' => 'andorra'));
		Country::create(array('country_name' => 'armenië'));
		Country::create(array('country_name' => 'azerbeidzjan'));
		Country::create(array('country_name' => 'belgië'));
		Country::create(array('country_name' => 'bosnië en herzegovina'));
		Country::create(array('country_name' => 'bulgarije'));
		Country::create(array('country_name' => 'cyprus'));
		Country::create(array('country_name' => 'denemarken'));
		Country::create(array('country_name' => 'duitsland'));
		Country::create(array('country_name' => 'estland'));
		Country::create(array('country_name' => 'faeroër'));
		Country::create(array('country_name' => 'finland'));
		Country::create(array('country_name' => 'frankrijk'));
		Country::create(array('country_name' => 'georgië'));
		Country::create(array('country_name' => 'griekenland'));
		Country::create(array('country_name' => 'groenland'));
		Country::create(array('country_name' => 'hongarije'));
		Country::create(array('country_name' => 'ierland'));
		Country::create(array('country_name' => 'ijsland'));
		Country::create(array('country_name' => 'italië'));
		Country::create(array('country_name' => 'kazachstan'));
		Country::create(array('country_name' => 'kosovo'));
		Country::create(array('country_name' => 'kroatië'));
		Country::create(array('country_name' => 'letland'));
		Country::create(array('country_name' => 'liechtenstein'));
		Country::create(array('country_name' => 'litouwen'));
		Country::create(array('country_name' => 'luxemburg'));
		Country::create(array('country_name' => 'macedonië'));
		Country::create(array('country_name' => 'malta'));
		Country::create(array('country_name' => 'moldavië'));
		Country::create(array('country_name' => 'monaco'));
		Country::create(array('country_name' => 'montenegro'));
		Country::create(array('country_name' => 'nederland'));
		Country::create(array('country_name' => 'noorwegen'));
		Country::create(array('country_name' => 'oekraïne'));
		Country::create(array('country_name' => 'oostenrijk'));
		Country::create(array('country_name' => 'polen'));
		Country::create(array('country_name' => 'portugal'));
		Country::create(array('country_name' => 'roemenië'));
		Country::create(array('country_name' => 'rusland'));
		Country::create(array('country_name' => 'san marino'));
		Country::create(array('country_name' => 'servië'));
		Country::create(array('country_name' => 'slovenië'));
		Country::create(array('country_name' => 'slowakije'));
		Country::create(array('country_name' => 'spanje'));
		Country::create(array('country_name' => 'tsjechië'));
		Country::create(array('country_name' => 'turkije'));
		Country::create(array('country_name' => 'vaticaanstad'));
		Country::create(array('country_name' => 'verenigd koninkrijk'));
		Country::create(array('country_name' => 'wit-rusland'));
		Country::create(array('country_name' => 'zweden'));
		Country::create(array('country_name' => 'zwitserland'));
		$this->command->info('Country created');

		$ProjectType1 = ProjectType::create(array('type_name' => 'regie'));
		$ProjectType2 = ProjectType::create(array('type_name' => 'calculatie'));
		$ProjectType3 = ProjectType::create(array('type_name' => 'blanco offerte & factuur'));
		$this->command->info('ProjectType created');

		$Part1 = Part::create(array('part_name' => 'contracting'));
		$Part2 = Part::create(array('part_name' => 'subcontracting'));
		$this->command->info('Part created');

		$PartType1 = PartType::create(array('type_name' => 'calculation'));
		$PartType2 = PartType::create(array('type_name' => 'estimate'));
		$this->command->info('PartType created');

		$Detail1 = Detail::create(array('detail_name' => 'more'));
		$Detail2 = Detail::create(array('detail_name' => 'less'));
		$this->command->info('Detail created');

		ContactFunction::create(array('function_name' => 'adjunct-directeur'));
		ContactFunction::create(array('function_name' => 'afdelingshoofd'));
		ContactFunction::create(array('function_name' => 'teamleider'));
		ContactFunction::create(array('function_name' => 'ploegbaas'));
		ContactFunction::create(array('function_name' => 'chef'));
		ContactFunction::create(array('function_name' => 'directeur'));
		ContactFunction::create(array('function_name' => 'onderdirecteur'));
		ContactFunction::create(array('function_name' => 'voorzitter'));
		ContactFunction::create(array('function_name' => 'hoofdingenieur'));
		ContactFunction::create(array('function_name' => 'ingenieur'));
		ContactFunction::create(array('function_name' => 'manager'));
		ContactFunction::create(array('function_name' => 'meester'));
		ContactFunction::create(array('function_name' => 'gezel'));
		ContactFunction::create(array('function_name' => 'leerling'));
		ContactFunction::create(array('function_name' => 'notaris'));
		ContactFunction::create(array('function_name' => 'boekhouder'));
		ContactFunction::create(array('function_name' => 'architect'));
		ContactFunction::create(array('function_name' => 'secretaresse'));
		ContactFunction::create(array('function_name' => 'programma manager'));
		ContactFunction::create(array('function_name' => 'projectleider'));
		ContactFunction::create(array('function_name' => 'inkoop medewerker'));
		ContactFunction::create(array('function_name' => 'makelaar'));
		ContactFunction::create(array('function_name' => 'adviseur'));
		ContactFunction::create(array('function_name' => 'uitvoerder'));
		ContactFunction::create(array('function_name' => 'werkvoorbereider'));
		ContactFunction::create(array('function_name' => 'tekenaar'));
		ContactFunction::create(array('function_name' => 'bestekschrijver'));
		ContactFunction::create(array('function_name' => 'calculator'));
		ContactFunction::create(array('function_name' => 'opdrachtgever'));
		ContactFunction::create(array('function_name' => 'particulier'));
		$this->command->info('ContactFunction created');

		RelationType::create(array('type_name' => 'aannemer'));
		RelationType::create(array('type_name' => 'adviesbureau'));
		RelationType::create(array('type_name' => 'afvalverwerker'));
		RelationType::create(array('type_name' => 'architect'));
		RelationType::create(array('type_name' => 'betonboorder'));
		RelationType::create(array('type_name' => 'betonstaalvlechter'));
		RelationType::create(array('type_name' => 'betontimmerman'));
		RelationType::create(array('type_name' => 'bouwgroothandel'));
		RelationType::create(array('type_name' => 'containerverhuur'));
		RelationType::create(array('type_name' => 'cv-installateur'));
		RelationType::create(array('type_name' => 'dakdekker'));
		RelationType::create(array('type_name' => 'elektricien'));
		RelationType::create(array('type_name' => 'gevelreiniger'));
		RelationType::create(array('type_name' => 'glazenwasser'));
		RelationType::create(array('type_name' => 'grondwerker'));
		RelationType::create(array('type_name' => 'ijzervlechter'));
		RelationType::create(array('type_name' => 'ingenieursbureau'));
		RelationType::create(array('type_name' => 'installateur'));
		RelationType::create(array('type_name' => 'interieurarchitect'));
		RelationType::create(array('type_name' => 'klusjesman'));
		RelationType::create(array('type_name' => 'loodgieter'));
		RelationType::create(array('type_name' => 'metselaar'));
		RelationType::create(array('type_name' => 'meubelmaker'));
		RelationType::create(array('type_name' => 'natuursteenwerker'));
		RelationType::create(array('type_name' => 'onderhoudsbedrijf'));		
		RelationType::create(array('type_name' => 'opdrachtgever'));
		RelationType::create(array('type_name' => 'overheid'));
		RelationType::create(array('type_name' => 'overig'));
		RelationType::create(array('type_name' => 'parketteur'));
		RelationType::create(array('type_name' => 'schilder'));
		RelationType::create(array('type_name' => 'schoonmaakbedrijf'));
		RelationType::create(array('type_name' => 'steigerbouwer'));
		RelationType::create(array('type_name' => 'stukadoor'));
		RelationType::create(array('type_name' => 'tegelzetter'));
		RelationType::create(array('type_name' => 'timmerman'));
		RelationType::create(array('type_name' => 'tuinman'));
		RelationType::create(array('type_name' => 'tussenpersoon'));
		RelationType::create(array('type_name' => 'vereniging van eigenaren'));
		RelationType::create(array('type_name' => 'verfgroothandel'));
		RelationType::create(array('type_name' => 'verhuurbedrijf'));
		RelationType::create(array('type_name' => 'verwarmingsmonteur'));
		RelationType::create(array('type_name' => 'vloerenlegger'));
		RelationType::create(array('type_name' => 'voeger'));
		RelationType::create(array('type_name' => 'woningbouwvereniging'));
		RelationType::create(array('type_name' => 'zonwering'));
		$this->command->info('RelationType created');

		WholesaleType::create(array('type_name' => 'bouw'));
		WholesaleType::create(array('type_name' => 'installatie'));
		WholesaleType::create(array('type_name' => 'ijzerwaren'));
		WholesaleType::create(array('type_name' => 'electra'));
		WholesaleType::create(array('type_name' => 'verf'));
		WholesaleType::create(array('type_name' => 'hovenier'));
		WholesaleType::create(array('type_name' => 'sanitair'));
		WholesaleType::create(array('type_name' => 'verhuur'));
		WholesaleType::create(array('type_name' => 'groothandel'));
		WholesaleType::create(array('type_name' => 'veiling'));
		WholesaleType::create(array('type_name' => 'overig'));
		$this->command->info('WholesaleType created');

		RelationKind::create(array('kind_name' => 'zakelijk'));
		RelationKind::create(array('kind_name' => 'particulier'));
		$this->command->info('RelationKind created');

		Valid::create(array('valid_name' => '5 dagen'));
		Valid::create(array('valid_name' => '14 dagen'));
		Valid::create(array('valid_name' => '30 dagen'));
		Valid::create(array('valid_name' => '2 maanden'));
		Valid::create(array('valid_name' => '3 maanden'));
		$this->command->info('Valid created');

		DeliverTime::create(array('delivertime_name' => 'per direct'));
		DeliverTime::create(array('delivertime_name' => 'in overleg'));
		DeliverTime::create(array('delivertime_name' => '1 week'));
		DeliverTime::create(array('delivertime_name' => '2 weken'));
		DeliverTime::create(array('delivertime_name' => '3 weken'));
		DeliverTime::create(array('delivertime_name' => '1 maand'));
		DeliverTime::create(array('delivertime_name' => '2 maanden'));
		DeliverTime::create(array('delivertime_name' => '3 maanden'));
		$this->command->info('DeliverTime created');

		Tax::create(array('tax_rate' => 0));
		Tax::create(array('tax_rate' => 6));
		Tax::create(array('tax_rate' => 21));
		$this->command->info('Tax created');

		TimesheetKind::create(array('kind_name' => 'aanneming'));
		TimesheetKind::create(array('kind_name' => 'stelpost'));
		TimesheetKind::create(array('kind_name' => 'meerwerk'));
		$this->command->info('TimesheetKind created');

		PurchaseKind::create(array('kind_name' => 'aanneming'));
		PurchaseKind::create(array('kind_name' => 'onderaanneming'));
		$this->command->info('PurchaseKind created');

		SysMessage::create(array('level' => 1, 'content' => 'Dit is een voorbeeld melding', 'active' => true));
		$this->command->info('SystemMessage created');
	}
 }
