<link rel="apple-touch-icon" type="image/png" sizes="57x57" href="/images/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="/images/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" type="image/png" sizes="72x72" href="/images/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="/images/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="114x114" href="/images/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="/images/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="144x144" href="/images/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" type="image/png" sizes="152x152" href="/images/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="/images/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" sizes="36x36" href="/images/android-chrome-36x36.png">
<link rel="icon" type="image/png" sizes="48x48" href="/images/android-chrome-48x48.png">
<link rel="icon" type="image/png" sizes="72x72" href="/images/android-chrome-72x72.png">
<link rel="icon" type="image/png" sizes="96x96" href="/images/android-chrome-96x96.png">
<link rel="icon" type="image/png" sizes="144x144" href="/images/android-chrome-144x144.png">
<link rel="icon" type="image/png" sizes="192x192" href="/images/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/images/favicon-96x96.png">
