<?php

/*
 * Static Models Only
 * Test are performed on other seeds
 */
class StaticSeeder extends Seeder {

	public function run()
	{

		DB::table('sub_group')->delete();
		DB::table('supplier')->delete();
		DB::table('tax')->delete();
		DB::table('system_option')->delete();
		DB::table('deliver_time')->delete();
		DB::table('valid')->delete();
		DB::table('relation_kind')->delete();
		DB::table('relation_type')->delete();
		DB::table('contact_function')->delete();
		DB::table('part_part_detail')->delete();
		DB::table('part_part_type')->delete();
		DB::table('part_type')->delete();
		DB::table('part')->delete();
		DB::table('project_type')->delete();
		DB::table('country')->delete();
		DB::table('province')->delete();
		DB::table('user_type')->delete();
		$this->command->info('Tables deleted');

		SubGroup::create(array('reference_code'=>'16-64-1','group_type'=>'Aardkleuren'));
		SubGroup::create(array('reference_code'=>'14-48-8','group_type'=>'Accessoires (Deel1)'));
		SubGroup::create(array('reference_code'=>'13-35-2','group_type'=>'Accessoires (Deel 2)'));
		SubGroup::create(array('reference_code'=>'14-40-5','group_type'=>'Afbouwersgereedschap'));
		SubGroup::create(array('reference_code'=>'14-46-18','group_type'=>'Afdekken'));
		SubGroup::create(array('reference_code'=>'14-42-4','group_type'=>'Afplakband/Tapes'));
		SubGroup::create(array('reference_code'=>'12-21-50','group_type'=>'Afvoeren En Toebehoren'));
		SubGroup::create(array('reference_code'=>'16-60-1','group_type'=>'Afwerkverf'));
		SubGroup::create(array('reference_code'=>'16-65-1','group_type'=>'Afwerkverven'));
		SubGroup::create(array('reference_code'=>'14-48-5','group_type'=>'Akkumachines'));
		SubGroup::create(array('reference_code'=>'10-10-6','group_type'=>'Aluminium Programma'));
		SubGroup::create(array('reference_code'=>'15-54-2','group_type'=>'Aluminiumprofielen'));
		SubGroup::create(array('reference_code'=>'15-54-3','group_type'=>'Ankerprogramma'));
		SubGroup::create(array('reference_code'=>'14-46-17','group_type'=>'Automotive'));
		SubGroup::create(array('reference_code'=>'12-25-8','group_type'=>'Badkuipen'));
		SubGroup::create(array('reference_code'=>'13-33-3','group_type'=>'Batterijen'));
		SubGroup::create(array('reference_code'=>'14-55-13','group_type'=>'Beitels'));
		SubGroup::create(array('reference_code'=>'16-61-1','group_type'=>'Beitsen'));
		SubGroup::create(array('reference_code'=>'16-61-99','group_type'=>'Beitsen Diversen'));
		SubGroup::create(array('reference_code'=>'13-31-21','group_type'=>'Berker'));
		SubGroup::create(array('reference_code'=>'10-6-1','group_type'=>'Beton Dakpannen'));
		SubGroup::create(array('reference_code'=>'10-11-3','group_type'=>'Beton Ijzer'));
		SubGroup::create(array('reference_code'=>'10-3-1','group_type'=>'Betontegels'));
		SubGroup::create(array('reference_code'=>'13-32-6','group_type'=>'Beveiliging'));
		SubGroup::create(array('reference_code'=>'12-21-18','group_type'=>'Bevest. Mat. Rk-Buis'));
		SubGroup::create(array('reference_code'=>'13-31-14','group_type'=>'Bevestigingsmat./Buis'));
		SubGroup::create(array('reference_code'=>'16-63-50','group_type'=>'Bison Professional Lijmen'));
		SubGroup::create(array('reference_code'=>'11-17-1','group_type'=>'Boarddeuren'));
		SubGroup::create(array('reference_code'=>'14-48-4','group_type'=>'Boorhamers/Hakhamers'));
		SubGroup::create(array('reference_code'=>'14-48-1','group_type'=>'Boormachines'));
		SubGroup::create(array('reference_code'=>'14-49-2','group_type'=>'Boren'));
		SubGroup::create(array('reference_code'=>'14-49-12','group_type'=>'Boren Diversen'));
		SubGroup::create(array('reference_code'=>'10-13-5','group_type'=>'Bouwmaat'));
		SubGroup::create(array('reference_code'=>'16-63-3','group_type'=>'Bouwmaat Kitten'));
		SubGroup::create(array('reference_code'=>'10-11-5','group_type'=>'Bouwprofielen'));
		SubGroup::create(array('reference_code'=>'11-17-6','group_type'=>'Branddeuren'));
		SubGroup::create(array('reference_code'=>'13-31-12','group_type'=>'Buig- En Trekveren'));
		SubGroup::create(array('reference_code'=>'12-21-35','group_type'=>'Buis Bevestigingsbeugels'));
		SubGroup::create(array('reference_code'=>'12-23-8','group_type'=>'Buisrozetten En Bevest.'));
		SubGroup::create(array('reference_code'=>'13-32-7','group_type'=>'Buitenverlichting'));
		SubGroup::create(array('reference_code'=>'13-32-2','group_type'=>'Bulleyes/Looplampen'));
		SubGroup::create(array('reference_code'=>'13-31-4','group_type'=>'Busch & Jager'));
		SubGroup::create(array('reference_code'=>'14-46-7','group_type'=>'Butaan/Propaangereedschap'));
		SubGroup::create(array('reference_code'=>'12-23-4','group_type'=>'C.V. Instal.Mat + Toebeh.'));
		SubGroup::create(array('reference_code'=>'12-23-2','group_type'=>'C.V. Ketels'));
		SubGroup::create(array('reference_code'=>'10-1-1','group_type'=>'Cement'));
		SubGroup::create(array('reference_code'=>'14-49-4','group_type'=>'Cirkelzaagbladen'));
		SubGroup::create(array('reference_code'=>'13-31-17','group_type'=>'Coax - Telefoon Aansl.'));
		SubGroup::create(array('reference_code'=>'12-24-22','group_type'=>'Comfort'));
		SubGroup::create(array('reference_code'=>'12-23-15','group_type'=>'Compact Radiatoren'));
		SubGroup::create(array('reference_code'=>'12-21-40','group_type'=>'Cv Fittingen'));
		SubGroup::create(array('reference_code'=>'10-6-99','group_type'=>'Dakbedekking Diversen'));
		SubGroup::create(array('reference_code'=>'10-5-16','group_type'=>'Dakplaten'));
		SubGroup::create(array('reference_code'=>'10-6-4','group_type'=>'Dakramen'));
		SubGroup::create(array('reference_code'=>'10-6-7','group_type'=>'Dakreparatie'));
		SubGroup::create(array('reference_code'=>'10-6-3','group_type'=>'Dakrollen'));
		SubGroup::create(array('reference_code'=>'16-62-99','group_type'=>'Decoratie Diversen'));
		SubGroup::create(array('reference_code'=>'14-49-3','group_type'=>'Decoupeerzaagbladen'));
		SubGroup::create(array('reference_code'=>'10-11-7','group_type'=>'Dekkleden'));
		SubGroup::create(array('reference_code'=>'12-23-14','group_type'=>'Design Radiatoren'));
		SubGroup::create(array('reference_code'=>'15-51-52','group_type'=>'Deurbeslag'));
		SubGroup::create(array('reference_code'=>'11-17-99','group_type'=>'Deuren Diversen'));
		SubGroup::create(array('reference_code'=>'14-48-7','group_type'=>'Div. Elek. Gereedschap'));
		SubGroup::create(array('reference_code'=>'15-51-57','group_type'=>'Div. Garnituren/Scharn.'));
		SubGroup::create(array('reference_code'=>'15-51-55','group_type'=>'Div.Hang- En Sluitwerk'));
		SubGroup::create(array('reference_code'=>'10-11-99','group_type'=>'Diversen (Deel 1)'));
		SubGroup::create(array('reference_code'=>'15-52-99','group_type'=>'Diversen (Deel 2)'));
		SubGroup::create(array('reference_code'=>'14-46-14','group_type'=>'Diversen (Deel 3)'));
		SubGroup::create(array('reference_code'=>'13-33-99','group_type'=>'Diversen (Deel 4)'));
		SubGroup::create(array('reference_code'=>'11-11-99','group_type'=>'Diversen Zachthout'));
		SubGroup::create(array('reference_code'=>'13-31-23','group_type'=>'Domotica'));
		SubGroup::create(array('reference_code'=>'14-46-3','group_type'=>'Dompelpompen'));
		SubGroup::create(array('reference_code'=>'12-24-7','group_type'=>'Douche Slangen'));
		SubGroup::create(array('reference_code'=>'12-25-9','group_type'=>'Douchebakken'));
		SubGroup::create(array('reference_code'=>'12-24-8','group_type'=>'Douchewand+Hoekinstap'));
		SubGroup::create(array('reference_code'=>'13-31-13','group_type'=>'Draad/Kabel'));
		SubGroup::create(array('reference_code'=>'14-55-16','group_type'=>'Drevels/Deuvels'));
		SubGroup::create(array('reference_code'=>'10-5-7','group_type'=>'Dubbele Beglazing'));
		SubGroup::create(array('reference_code'=>'12-25-5','group_type'=>'Duobloks'));
		SubGroup::create(array('reference_code'=>'10-13-1','group_type'=>'Eurocol'));
		SubGroup::create(array('reference_code'=>'12-23-7','group_type'=>'Expansievaten En Toebeh.'));
		SubGroup::create(array('reference_code'=>'14-48-9','group_type'=>'Fein Macines'));
		SubGroup::create(array('reference_code'=>'14-49-14','group_type'=>'Fein Toebehoren'));
		SubGroup::create(array('reference_code'=>'10-4-4','group_type'=>'Fermacell'));
		SubGroup::create(array('reference_code'=>'15-52-51','group_type'=>'Fis Profi Bouten & Schr.'));
		SubGroup::create(array('reference_code'=>'15-52-52','group_type'=>'Fis Profi Draadnagels'));
		SubGroup::create(array('reference_code'=>'12-21-36','group_type'=>'Flexibele Beschermbuis'));
		SubGroup::create(array('reference_code'=>'12-21-42','group_type'=>'Flexibele Slangen'));
		SubGroup::create(array('reference_code'=>'10-5-8','group_type'=>'Folieen'));
		SubGroup::create(array('reference_code'=>'12-25-4','group_type'=>'Fonteinen'));
		SubGroup::create(array('reference_code'=>'14-49-10','group_type'=>'Frezen'));
		SubGroup::create(array('reference_code'=>'12-23-9','group_type'=>'Gas Artikelen Sanivesk'));
		SubGroup::create(array('reference_code'=>'10-2-3','group_type'=>'Gasbet0N -En Gipsblokken'));
		SubGroup::create(array('reference_code'=>'12-21-20','group_type'=>'Gaskranen En -Slangen'));
		SubGroup::create(array('reference_code'=>'12-23-1','group_type'=>'Geisers En Boilers'));
		SubGroup::create(array('reference_code'=>'11-16-1','group_type'=>'Gemelamineerd Spaanplaat'));
		SubGroup::create(array('reference_code'=>'11-11-4','group_type'=>'Gemodificeerd Hout'));
		SubGroup::create(array('reference_code'=>'11-12-1','group_type'=>'Geschaafd'));
		SubGroup::create(array('reference_code'=>'10-1-4','group_type'=>'Gips + Kalk'));
		SubGroup::create(array('reference_code'=>'10-4-1','group_type'=>'Gipsplaat'));
		SubGroup::create(array('reference_code'=>'13-31-24','group_type'=>'Gira'));
		SubGroup::create(array('reference_code'=>'11-14-1','group_type'=>'Glaslatten'));
		SubGroup::create(array('reference_code'=>'10-5-1','group_type'=>'Glaswolrollen/Platen'));
		SubGroup::create(array('reference_code'=>'10-11-9','group_type'=>'Glazen Bouwstenen'));
		SubGroup::create(array('reference_code'=>'12-24-5','group_type'=>'Glijstangsets'));
		SubGroup::create(array('reference_code'=>'10-6-6','group_type'=>'Golfplaten'));
		SubGroup::create(array('reference_code'=>'15-54-8','group_type'=>'Gordijnrails'));
		SubGroup::create(array('reference_code'=>'15-51-51','group_type'=>'Grendel/Sluiting/Schuiven'));
		SubGroup::create(array('reference_code'=>'10-3-2','group_type'=>'Grindtegels'));
		SubGroup::create(array('reference_code'=>'13-31-11','group_type'=>'Groepenkasten'));
		SubGroup::create(array('reference_code'=>'12-26-3','group_type'=>'Grohe Kranen Eurodisc'));
		SubGroup::create(array('reference_code'=>'12-26-17','group_type'=>'Grohe Kranen Eurosmart'));
		SubGroup::create(array('reference_code'=>'12-26-16','group_type'=>'Grohe Kranen Thermostaat'));
		SubGroup::create(array('reference_code'=>'12-26-19','group_type'=>'Grohe Supra'));
		SubGroup::create(array('reference_code'=>'13-32-3','group_type'=>'Halogeenlampen'));
		SubGroup::create(array('reference_code'=>'13-34-1','group_type'=>'Halogeenspots'));
		SubGroup::create(array('reference_code'=>'14-55-10','group_type'=>'Hamers'));
		SubGroup::create(array('reference_code'=>'12-24-6','group_type'=>'Handdouches'));
		SubGroup::create(array('reference_code'=>'14-55-21','group_type'=>'Handgereedschap Diversen'));
		SubGroup::create(array('reference_code'=>'11-15-3','group_type'=>'Hardboard'));
		SubGroup::create(array('reference_code'=>'14-48-6','group_type'=>'Hechtapparaten'));
		SubGroup::create(array('reference_code'=>'12-22-3','group_type'=>'Hemelwaterafv.Bakken+Goot'));
		SubGroup::create(array('reference_code'=>'12-22-4','group_type'=>'Hemelwaterafv.Hulpstukken'));
		SubGroup::create(array('reference_code'=>'15-54-9','group_type'=>'Horren'));
		SubGroup::create(array('reference_code'=>'15-54-4','group_type'=>'Hout- En Bouwankers'));
		SubGroup::create(array('reference_code'=>'15-52-2','group_type'=>'Houtschroeven Vk En Pk'));
		SubGroup::create(array('reference_code'=>'18-81-3','group_type'=>'Inbouwkookplaten'));
		SubGroup::create(array('reference_code'=>'18-81-5','group_type'=>'Inbouwovens'));
		SubGroup::create(array('reference_code'=>'13-31-9','group_type'=>'Installatie Materiaal'));
		SubGroup::create(array('reference_code'=>'13-31-99','group_type'=>'Installatiemat. Diversen'));
		SubGroup::create(array('reference_code'=>'13-31-10','group_type'=>'Isolatie Aard/Zekering'));
		SubGroup::create(array('reference_code'=>'10-5-99','group_type'=>'Isolatie Diversen'));
		SubGroup::create(array('reference_code'=>'13-31-20','group_type'=>'Jung'));
		SubGroup::create(array('reference_code'=>'13-31-16','group_type'=>'K25+K40 Systeem'));
		SubGroup::create(array('reference_code'=>'14-60-1','group_type'=>'Keetconcept'));
		SubGroup::create(array('reference_code'=>'14-61-1','group_type'=>'Keetconcept 0,06'));
		SubGroup::create(array('reference_code'=>'10-6-2','group_type'=>'Keramische Pannen'));
		SubGroup::create(array('reference_code'=>'15-54-12','group_type'=>'Ketting'));
		SubGroup::create(array('reference_code'=>'16-63-5','group_type'=>'Kitten'));
		SubGroup::create(array('reference_code'=>'14-46-12','group_type'=>'Kleding'));
		SubGroup::create(array('reference_code'=>'16-65-4','group_type'=>'Kleurenwaaiers'));
		SubGroup::create(array('reference_code'=>'12-25-6','group_type'=>'Klosetpotten'));
		SubGroup::create(array('reference_code'=>'12-26-18','group_type'=>'Kludi Kranen'));
		SubGroup::create(array('reference_code'=>'12-21-31','group_type'=>'Knelfittingen'));
		SubGroup::create(array('reference_code'=>'12-21-38','group_type'=>'Knelstopkraan Sanivesk'));
		SubGroup::create(array('reference_code'=>'15-51-56','group_type'=>'Knoppen/Grepen/Haken'));
		SubGroup::create(array('reference_code'=>'18-81-7','group_type'=>'Koelautomaten'));
		SubGroup::create(array('reference_code'=>'13-31-15','group_type'=>'Kontakt-Materiaal'));
		SubGroup::create(array('reference_code'=>'11-14-3','group_type'=>'Kop-,Hoek- En Hollatten'));
		SubGroup::create(array('reference_code'=>'11-18-3','group_type'=>'Kozijn- En Raamprofielen'));
		SubGroup::create(array('reference_code'=>'12-21-46','group_type'=>'Kraan Toebehoren'));
		SubGroup::create(array('reference_code'=>'12-26-4','group_type'=>'Kraankoppelingen'));
		SubGroup::create(array('reference_code'=>'18-82-2','group_type'=>'Kunststof'));
		SubGroup::create(array('reference_code'=>'15-54-1','group_type'=>'Kunststof Profielen/Strip'));
		SubGroup::create(array('reference_code'=>'11-13-6','group_type'=>'Kunststof Schroten'));
		SubGroup::create(array('reference_code'=>'11-15-7','group_type'=>'Kunststofplaten'));
		SubGroup::create(array('reference_code'=>'14-42-1','group_type'=>'Kwasten'));
		SubGroup::create(array('reference_code'=>'14-50-1','group_type'=>'Ladders En Trappen'));
		SubGroup::create(array('reference_code'=>'16-61-2','group_type'=>'Lakken'));
		SubGroup::create(array('reference_code'=>'11-20-2','group_type'=>'Laminaat'));
		SubGroup::create(array('reference_code'=>'13-32-5','group_type'=>'Lampen'));
		SubGroup::create(array('reference_code'=>'13-31-7','group_type'=>'Lamphouders'));
		SubGroup::create(array('reference_code'=>'10-11-1','group_type'=>'Lateien'));
		SubGroup::create(array('reference_code'=>'16-60-2','group_type'=>'Latex/Muurverven'));
		SubGroup::create(array('reference_code'=>'14-46-8','group_type'=>'Lederen Gereedschaphouder'));
		SubGroup::create(array('reference_code'=>'10-5-5','group_type'=>'Leiding Isolatie'));
		SubGroup::create(array('reference_code'=>'10-11-2','group_type'=>'Lewisplaten'));
		SubGroup::create(array('reference_code'=>'10-6-5','group_type'=>'Lichtkoepels'));
		SubGroup::create(array('reference_code'=>'16-63-1','group_type'=>'Lijmen Div.'));
		SubGroup::create(array('reference_code'=>'11-14-7','group_type'=>'Lijstwerk Diversen'));
		SubGroup::create(array('reference_code'=>'12-24-25','group_type'=>'Linido'));
		SubGroup::create(array('reference_code'=>'15-50-3','group_type'=>'Luxe Sierbeslag'));
		SubGroup::create(array('reference_code'=>'18-81-9','group_type'=>'Magnetrons'));
		SubGroup::create(array('reference_code'=>'12-21-39','group_type'=>'Malleabele Fittingen'));
		SubGroup::create(array('reference_code'=>'11-16-2','group_type'=>'Massief Vuren/Grenen'));
		SubGroup::create(array('reference_code'=>'14-55-19','group_type'=>'Meet/Aftekengereedschap'));
		SubGroup::create(array('reference_code'=>'11-17-3','group_type'=>'Meranti Deuren'));
		SubGroup::create(array('reference_code'=>'11-17-4','group_type'=>'Merbau Deuren'));
		SubGroup::create(array('reference_code'=>'12-24-13','group_type'=>'Metaal Eclips Chroom'));
		SubGroup::create(array('reference_code'=>'14-40-99','group_type'=>'Metsel&Bouwgereeds. Div.'));
		SubGroup::create(array('reference_code'=>'14-40-4','group_type'=>'Metselaarsgereedschap'));
		SubGroup::create(array('reference_code'=>'10-2-1','group_type'=>'Metselbakstenen'));
		SubGroup::create(array('reference_code'=>'10-9-10','group_type'=>'Metzger'));
		SubGroup::create(array('reference_code'=>'11-16-99','group_type'=>'Meubelpanelen Diversen'));
		SubGroup::create(array('reference_code'=>'14-46-5','group_type'=>'Mortelkuipen/Betonmolens'));
		SubGroup::create(array('reference_code'=>'10-1-3','group_type'=>'Mortels'));
		SubGroup::create(array('reference_code'=>'10-7-7','group_type'=>'Mosa Wandtegels'));
		SubGroup::create(array('reference_code'=>'11-15-1','group_type'=>'Multiplex'));
		SubGroup::create(array('reference_code'=>'12-24-23','group_type'=>'Murcia'));
		SubGroup::create(array('reference_code'=>'15-52-19','group_type'=>'Nagels Diversen'));
		SubGroup::create(array('reference_code'=>'10-2-5','group_type'=>'Natuursteen'));
		SubGroup::create(array('reference_code'=>'14-49-8','group_type'=>'Nieten'));
		SubGroup::create(array('reference_code'=>'13-31-1','group_type'=>'Opbouw Materiaal'));
		SubGroup::create(array('reference_code'=>'10-11-6','group_type'=>'Open Haarden'));
		SubGroup::create(array('reference_code'=>'10-3-4','group_type'=>'Opsluitbanden'));
		SubGroup::create(array('reference_code'=>'12-25-10','group_type'=>'Overig Plaatstaal Sanit.'));
		SubGroup::create(array('reference_code'=>'12-26-8','group_type'=>'Overige Toebehoren Kranen'));
		SubGroup::create(array('reference_code'=>'11-14-6','group_type'=>'Overzetplinten E.D.'));
		SubGroup::create(array('reference_code'=>'12-22-99','group_type'=>'P.V.C. Diversen'));
		SubGroup::create(array('reference_code'=>'13-35-1','group_type'=>'Panelen'));
		SubGroup::create(array('reference_code'=>'11-20-1','group_type'=>'Parkethout'));
		SubGroup::create(array('reference_code'=>'13-31-22','group_type'=>'Peha'));
		SubGroup::create(array('reference_code'=>'14-49-13','group_type'=>'Perflex'));
		SubGroup::create(array('reference_code'=>'13-31-3','group_type'=>'Perilex'));
		SubGroup::create(array('reference_code'=>'14-46-9','group_type'=>'Persoonlijke Bescherming'));
		SubGroup::create(array('reference_code'=>'12-21-56','group_type'=>'Pexfit'));
		SubGroup::create(array('reference_code'=>'10-4-99','group_type'=>'Plaatmat. Bouw Diversen'));
		SubGroup::create(array('reference_code'=>'11-21-2','group_type'=>'Plafondplaten'));
		SubGroup::create(array('reference_code'=>'10-11-10','group_type'=>'Plafondsystemen'));
		SubGroup::create(array('reference_code'=>'13-34-3','group_type'=>'Plafonniers'));
		SubGroup::create(array('reference_code'=>'12-25-3','group_type'=>'Planchets'));
		SubGroup::create(array('reference_code'=>'15-54-5','group_type'=>'Plankdragers'));
		SubGroup::create(array('reference_code'=>'10-10-5','group_type'=>'Platte Buis Systeem'));
		SubGroup::create(array('reference_code'=>'11-12-99','group_type'=>'Plinten'));
		SubGroup::create(array('reference_code'=>'15-52-25','group_type'=>'Pluggen'));
		SubGroup::create(array('reference_code'=>'10-6-9','group_type'=>'Polycarb./Plexiglas'));
		SubGroup::create(array('reference_code'=>'10-5-3','group_type'=>'Polystyreen Platen'));
		SubGroup::create(array('reference_code'=>'12-21-32','group_type'=>'Push-In Steekfittingen'));
		SubGroup::create(array('reference_code'=>'10-8-2','group_type'=>'Raamdorpelstenen'));
		SubGroup::create(array('reference_code'=>'15-51-53','group_type'=>'Raamsluitwerk'));
		SubGroup::create(array('reference_code'=>'12-23-6','group_type'=>'Radiator En Cv Toebehoren'));
		SubGroup::create(array('reference_code'=>'10-9-6','group_type'=>'Reiniging + Onderhoud'));
		SubGroup::create(array('reference_code'=>'16-60-4','group_type'=>'Reiniging En Verdunning'));
		SubGroup::create(array('reference_code'=>'12-21-47','group_type'=>'Reservoir Toebehoren'));
		SubGroup::create(array('reference_code'=>'12-25-7','group_type'=>'Reservoirs'));
		SubGroup::create(array('reference_code'=>'12-21-49','group_type'=>'Ringen En Schijfjes'));
		SubGroup::create(array('reference_code'=>'15-52-21','group_type'=>'Ringen,Draadstangen'));
		SubGroup::create(array('reference_code'=>'12-22-1','group_type'=>'Riolering Buizen'));
		SubGroup::create(array('reference_code'=>'12-22-2','group_type'=>'Riolering Hulpstukken'));
		SubGroup::create(array('reference_code'=>'14-42-2','group_type'=>'Rollers'));
		SubGroup::create(array('reference_code'=>'11-14-4','group_type'=>'Rond/Halfrond/Kwartrond'));
		SubGroup::create(array('reference_code'=>'12-21-9','group_type'=>'Rood Koperen Buis'));
		SubGroup::create(array('reference_code'=>'12-21-34','group_type'=>'Roodkoperen Fittingen'));
		SubGroup::create(array('reference_code'=>'10-10-7','group_type'=>'Rookgas Afvoer'));
		SubGroup::create(array('reference_code'=>'10-10-2','group_type'=>'Rookgasdoorvoer'));
		SubGroup::create(array('reference_code'=>'15-54-50','group_type'=>'Roosters'));
		SubGroup::create(array('reference_code'=>'14-41-1','group_type'=>'Rothenberger'));
		SubGroup::create(array('reference_code'=>'12-21-45','group_type'=>'Rozetten En Verlengst.Chr'));
		SubGroup::create(array('reference_code'=>'18-82-1','group_type'=>'Rvs'));
		SubGroup::create(array('reference_code'=>'12-24-99','group_type'=>'Sanitair Accessoires Div.'));
		SubGroup::create(array('reference_code'=>'12-21-43','group_type'=>'Sanitair Bevest.Materiaal'));
		SubGroup::create(array('reference_code'=>'15-51-54','group_type'=>'Scharnieren'));
		SubGroup::create(array('reference_code'=>'10-4-2','group_type'=>'Scheidingswand'));
		SubGroup::create(array('reference_code'=>'13-33-2','group_type'=>'Schel/Travo/Buitendeurdr.'));
		SubGroup::create(array('reference_code'=>'14-42-3','group_type'=>'Schildersgereedschappen'));
		SubGroup::create(array('reference_code'=>'10-13-2','group_type'=>'Schonox'));
		SubGroup::create(array('reference_code'=>'14-50-3','group_type'=>'Schragen En Bokken'));
		SubGroup::create(array('reference_code'=>'14-49-7','group_type'=>'Schroefbits'));
		SubGroup::create(array('reference_code'=>'15-52-10','group_type'=>'Schroeven Diversen'));
		SubGroup::create(array('reference_code'=>'14-55-14','group_type'=>'Schroevendraaiers'));
		SubGroup::create(array('reference_code'=>'11-13-2','group_type'=>'Schroten Hardhout'));
		SubGroup::create(array('reference_code'=>'11-13-1','group_type'=>'Schroten Zachthout'));
		SubGroup::create(array('reference_code'=>'11-17-21','group_type'=>'Schuifdeursystemen'));
		SubGroup::create(array('reference_code'=>'14-49-6','group_type'=>'Schuurpapier'));
		SubGroup::create(array('reference_code'=>'16-65-2','group_type'=>'Sierpleisters (Deel 2)'));
		SubGroup::create(array('reference_code'=>'16-62-1','group_type'=>'Sierpleisters (Deel 1)'));
		SubGroup::create(array('reference_code'=>'16-66-5','group_type'=>'Sikkens'));
		SubGroup::create(array('reference_code'=>'14-46-4','group_type'=>'Slangen En Toebehoren'));
		SubGroup::create(array('reference_code'=>'14-48-3','group_type'=>'Slijpmachines'));
		SubGroup::create(array('reference_code'=>'14-49-5','group_type'=>'Slijpschijven,Borstels'));
		SubGroup::create(array('reference_code'=>'15-51-50','group_type'=>'Sloten'));
		SubGroup::create(array('reference_code'=>'12-21-33','group_type'=>'Soldeer/Draadfittingen'));
		SubGroup::create(array('reference_code'=>'12-21-30','group_type'=>'Soldeerfittingen'));
		SubGroup::create(array('reference_code'=>'14-55-18','group_type'=>'Soldeergereedschap'));
		SubGroup::create(array('reference_code'=>'11-15-2','group_type'=>'Spaanplaat'));
		SubGroup::create(array('reference_code'=>'15-52-5','group_type'=>'Spaanplaatschroeven'));
		SubGroup::create(array('reference_code'=>'12-24-4','group_type'=>'Spiegels'));
		SubGroup::create(array('reference_code'=>'10-10-3','group_type'=>'Spirovent Buizen & Hulpst'));
		SubGroup::create(array('reference_code'=>'18-82-3','group_type'=>'Spoelbakken'));
		SubGroup::create(array('reference_code'=>'11-18-1','group_type'=>'Standaard Kozijnen Hout'));
		SubGroup::create(array('reference_code'=>'11-18-2','group_type'=>'Standaard Kozijnen Metaal'));
		SubGroup::create(array('reference_code'=>'14-55-20','group_type'=>'Stanley Messen'));
		SubGroup::create(array('reference_code'=>'10-5-2','group_type'=>'Steenwolrollen/Platen'));
		SubGroup::create(array('reference_code'=>'14-50-4','group_type'=>'Steigers En Toebehoren'));
		SubGroup::create(array('reference_code'=>'13-31-8','group_type'=>'Stekker/Snoerschakelaar'));
		SubGroup::create(array('reference_code'=>'10-11-4','group_type'=>'Stelblokjes,Afstandhouder'));
		SubGroup::create(array('reference_code'=>'11-17-5','group_type'=>'Stijldeuren /Lbp Deuren'));
		SubGroup::create(array('reference_code'=>'14-46-2','group_type'=>'Stofzuigers'));
		SubGroup::create(array('reference_code'=>'12-21-37','group_type'=>'Stopkranen'));
		SubGroup::create(array('reference_code'=>'14-40-1','group_type'=>'Stucadoorsgereedschap'));
		SubGroup::create(array('reference_code'=>'15-54-16','group_type'=>'Stukadoorsprofielen'));
		SubGroup::create(array('reference_code'=>'10-5-4','group_type'=>'Styrofoam Platen'));
		SubGroup::create(array('reference_code'=>'13-32-4','group_type'=>'T.L.'));
		SubGroup::create(array('reference_code'=>'13-31-6','group_type'=>'Tafelkontaktdoos'));
		SubGroup::create(array('reference_code'=>'14-55-17','group_type'=>'Tangen'));
		SubGroup::create(array('reference_code'=>'12-21-44','group_type'=>'Tapkranen En Toebehoren'));
		SubGroup::create(array('reference_code'=>'14-40-2','group_type'=>'Tegelzettersgereedschap'));
		SubGroup::create(array('reference_code'=>'15-54-10','group_type'=>'Tochtprofielen'));
		SubGroup::create(array('reference_code'=>'14-49-11','group_type'=>'Toeb.Elek.Gereedschap Div'));
		SubGroup::create(array('reference_code'=>'12-23-3','group_type'=>'Toebehoren C.V. Radiators'));
		SubGroup::create(array('reference_code'=>'10-9-1','group_type'=>'Toeslag- En Hulpstoffen'));
		SubGroup::create(array('reference_code'=>'12-24-3','group_type'=>'Toiletzittingen'));
		SubGroup::create(array('reference_code'=>'15-54-6','group_type'=>'Touw'));
		SubGroup::create(array('reference_code'=>'14-46-6','group_type'=>'Tuingereedschap'));
		SubGroup::create(array('reference_code'=>'11-11-6','group_type'=>'Tuinhout'));
		SubGroup::create(array('reference_code'=>'12-21-41','group_type'=>'Tyleenbuis En Koppelingen'));
		SubGroup::create(array('reference_code'=>'10-5-11','group_type'=>'Unidek Dakisolatieplaat'));
		SubGroup::create(array('reference_code'=>'10-5-10','group_type'=>'Unidek Spouwisolatieplaat'));
		SubGroup::create(array('reference_code'=>'12-21-57','group_type'=>'Uponor'));
		SubGroup::create(array('reference_code'=>'14-46-1','group_type'=>'Vegers/Bezems'));
		SubGroup::create(array('reference_code'=>'14-46-13','group_type'=>'Veiligh.Schoenen&Laarzen'));
		SubGroup::create(array('reference_code'=>'12-26-15','group_type'=>'Venlo Kranen Nimbus Serie'));
		SubGroup::create(array('reference_code'=>'11-16-3','group_type'=>'Vensterbanken/Werkbladen'));
		SubGroup::create(array('reference_code'=>'10-10-1','group_type'=>'Ventilatie Dakdoorvoer'));
		SubGroup::create(array('reference_code'=>'13-33-1','group_type'=>'Ventilatoren'));
		SubGroup::create(array('reference_code'=>'13-32-99','group_type'=>'Verlichting Diversen'));
		SubGroup::create(array('reference_code'=>'14-55-11','group_type'=>'Vijlen / Raspen'));
		SubGroup::create(array('reference_code'=>'11-13-3','group_type'=>'Vloerdelen E.D. Zachthout'));
		SubGroup::create(array('reference_code'=>'14-40-3','group_type'=>'Vloerleggersgereedschap'));
		SubGroup::create(array('reference_code'=>'10-7-2','group_type'=>'Vloertegels'));
		SubGroup::create(array('reference_code'=>'12-23-10','group_type'=>'Vloerverwarming'));
		SubGroup::create(array('reference_code'=>'10-13-3','group_type'=>'Vn-Ci'));
		SubGroup::create(array('reference_code'=>'15-54-15','group_type'=>'Voetroosters'));
		SubGroup::create(array('reference_code'=>'16-60-3','group_type'=>'Voorbehandelingsprod.'));
		SubGroup::create(array('reference_code'=>'16-65-3','group_type'=>'Voorstrijk (Deel 2)'));
		SubGroup::create(array('reference_code'=>'16-62-2','group_type'=>'Voorstrijk (Deel 1)'));
		SubGroup::create(array('reference_code'=>'16-63-2','group_type'=>'Vulmiddelen'));
		SubGroup::create(array('reference_code'=>'11-11-3','group_type'=>'Vuren Geschaafd'));
		SubGroup::create(array('reference_code'=>'11-17-12','group_type'=>'Vuren Houten Deuren'));
		SubGroup::create(array('reference_code'=>'11-11-1','group_type'=>'Vuren Ruig'));
		SubGroup::create(array('reference_code'=>'15-54-7','group_type'=>'Wandrailsysteem'));
		SubGroup::create(array('reference_code'=>'10-7-1','group_type'=>'Wandtegels'));
		SubGroup::create(array('reference_code'=>'18-81-1','group_type'=>'Wasemkappen'));
		SubGroup::create(array('reference_code'=>'12-21-48','group_type'=>'Wasmachine Toebehoren'));
		SubGroup::create(array('reference_code'=>'12-25-1','group_type'=>'Wastafels'));
		SubGroup::create(array('reference_code'=>'13-31-2','group_type'=>'Waterd. Opb./Inb. Mat.'));
		SubGroup::create(array('reference_code'=>'14-48-2','group_type'=>'Zaag-,Schuur-Schaafmach.'));
		SubGroup::create(array('reference_code'=>'14-55-12','group_type'=>'Zagen'));
		SubGroup::create(array('reference_code'=>'10-1-2','group_type'=>'Zand+Grind'));
		SubGroup::create(array('reference_code'=>'16-63-4','group_type'=>'Zwaluw Lijmen En Kitten'));
		$this->command->info('SubGroup created');

		Supplier::create(array('supplier_name' => 'Bouwmaat'));
		$this->command->info('Supplier created');

		UserType::create(array('user_type' => 'system'));
		UserType::create(array('user_type' => 'admin'));
		UserType::create(array('user_type' => 'user'));
		UserType::create(array('user_type' => 'guest'));
		UserType::create(array('user_type' => 'tester'));
		UserType::create(array('user_type' => 'demo'));
		$this->command->info('UserType created');

		Province::create(array('province_name' => 'groningen'));
		Province::create(array('province_name' => 'friesland'));
		Province::create(array('province_name' => 'drenthe'));
		Province::create(array('province_name' => 'overijssel'));
		Province::create(array('province_name' => 'flevoland'));
		Province::create(array('province_name' => 'gelderland'));
		Province::create(array('province_name' => 'utrecht'));
		Province::create(array('province_name' => 'noord-holland'));
		Province::create(array('province_name' => 'zuid-holland'));
		Province::create(array('province_name' => 'noord-brabant'));
		Province::create(array('province_name' => 'limburg'));
		Province::create(array('province_name' => 'zeeland'));
		Province::create(array('province_name' => 'overig'));
		$this->command->info('Provance created');

		Country::create(array('country_name' => 'albanië'));
		Country::create(array('country_name' => 'andorra'));
		Country::create(array('country_name' => 'armenië'));
		Country::create(array('country_name' => 'azerbeidzjan'));
		Country::create(array('country_name' => 'belgië'));
		Country::create(array('country_name' => 'bosnië en herzegovina'));
		Country::create(array('country_name' => 'bulgarije'));
		Country::create(array('country_name' => 'cyprus'));
		Country::create(array('country_name' => 'denemarken'));
		Country::create(array('country_name' => 'duitsland'));
		Country::create(array('country_name' => 'estland'));
		Country::create(array('country_name' => 'faeroër'));
		Country::create(array('country_name' => 'finland'));
		Country::create(array('country_name' => 'frankrijk'));
		Country::create(array('country_name' => 'georgië'));
		Country::create(array('country_name' => 'griekenland'));
		Country::create(array('country_name' => 'groenland'));
		Country::create(array('country_name' => 'hongarije'));
		Country::create(array('country_name' => 'ierland'));
		Country::create(array('country_name' => 'ijsland'));
		Country::create(array('country_name' => 'italië'));
		Country::create(array('country_name' => 'kazachstan'));
		Country::create(array('country_name' => 'kosovo'));
		Country::create(array('country_name' => 'kroatië'));
		Country::create(array('country_name' => 'letland'));
		Country::create(array('country_name' => 'liechtenstein'));
		Country::create(array('country_name' => 'litouwen'));
		Country::create(array('country_name' => 'luxemburg'));
		Country::create(array('country_name' => 'macedonië'));
		Country::create(array('country_name' => 'malta'));
		Country::create(array('country_name' => 'moldavië'));
		Country::create(array('country_name' => 'monaco'));
		Country::create(array('country_name' => 'montenegro'));
		Country::create(array('country_name' => 'nederland'));
		Country::create(array('country_name' => 'noorwegen'));
		Country::create(array('country_name' => 'oekraïne'));
		Country::create(array('country_name' => 'oostenrijk'));
		Country::create(array('country_name' => 'polen'));
		Country::create(array('country_name' => 'portugal'));
		Country::create(array('country_name' => 'roemenië'));
		Country::create(array('country_name' => 'rusland'));
		Country::create(array('country_name' => 'san marino'));
		Country::create(array('country_name' => 'servië'));
		Country::create(array('country_name' => 'slovenië'));
		Country::create(array('country_name' => 'slowakije'));
		Country::create(array('country_name' => 'spanje'));
		Country::create(array('country_name' => 'tsjechië'));
		Country::create(array('country_name' => 'turkije'));
		Country::create(array('country_name' => 'vaticaanstad'));
		Country::create(array('country_name' => 'verenigd koninkrijk'));
		Country::create(array('country_name' => 'wit-rusland'));
		Country::create(array('country_name' => 'zweden'));
		Country::create(array('country_name' => 'zwitserland'));
		$this->command->info('Country created');

		$ProjectType1 = ProjectType::create(array('type_name' => 'regie'));
		$ProjectType2 = ProjectType::create(array('type_name' => 'calculatie'));
		$ProjectType3 = ProjectType::create(array('type_name' => 'blanco offerte'));
		$ProjectType4 = ProjectType::create(array('type_name' => 'blanco factuur'));
		$this->command->info('ProjectType created');

		$Part1 = Part::create(array('part_name' => 'contracting'));
		$Part2 = Part::create(array('part_name' => 'subcontracting'));
		$this->command->info('Part created');

		$PartType1 = PartType::create(array('type_name' => 'calculation'));
		$PartType2 = PartType::create(array('type_name' => 'estimate'));
		$this->command->info('PartType created');

		$Part1->partType()->attach($PartType1->id);
		$Part1->partType()->attach($PartType2->id);

		$Part2->partType()->attach($PartType1->id);
		$Part2->partType()->attach($PartType2->id);
		$this->command->info('Part / PartType attached');

		$Detail1 = Detail::create(array('detail_name' => 'more'));
		$Detail2 = Detail::create(array('detail_name' => 'less'));
		$this->command->info('Detail created');

		$PartType1->detail()->attach($Detail1->id);
		$PartType1->detail()->attach($Detail2->id);
		$this->command->info('PartType / Detail attached');

		ContactFunction::create(array('function_name' => 'adjunct-directeur'));
		ContactFunction::create(array('function_name' => 'afdelingshoofd'));
		ContactFunction::create(array('function_name' => 'teamleider'));
		ContactFunction::create(array('function_name' => 'ploegbaas'));
		ContactFunction::create(array('function_name' => 'chef'));
		ContactFunction::create(array('function_name' => 'directeur'));
		ContactFunction::create(array('function_name' => 'onderdirecteur'));
		ContactFunction::create(array('function_name' => 'voorzitter'));
		ContactFunction::create(array('function_name' => 'hoofdingenieur'));
		ContactFunction::create(array('function_name' => 'ingenieur'));
		ContactFunction::create(array('function_name' => 'manager'));
		ContactFunction::create(array('function_name' => 'meester'));
		ContactFunction::create(array('function_name' => 'gezel'));
		ContactFunction::create(array('function_name' => 'leerling'));
		ContactFunction::create(array('function_name' => 'notaris'));
		ContactFunction::create(array('function_name' => 'boekhouder'));
		ContactFunction::create(array('function_name' => 'architect'));
		ContactFunction::create(array('function_name' => 'secretaresse'));
		ContactFunction::create(array('function_name' => 'programma manager'));
		ContactFunction::create(array('function_name' => 'projectleider'));
		ContactFunction::create(array('function_name' => 'inkoop medewerker'));
		ContactFunction::create(array('function_name' => 'makelaar'));
		ContactFunction::create(array('function_name' => 'adviseur'));
		ContactFunction::create(array('function_name' => 'uitvoerder'));
		ContactFunction::create(array('function_name' => 'werkvoorbereider'));
		ContactFunction::create(array('function_name' => 'tekenaar'));
		ContactFunction::create(array('function_name' => 'bestekschrijver'));
		ContactFunction::create(array('function_name' => 'calculator'));
		$this->command->info('ContactFunction created');

		RelationType::create(array('type_name' => 'aannemer'));
		RelationType::create(array('type_name' => 'adviesbureau'));
		RelationType::create(array('type_name' => 'afvalverwerker'));
		RelationType::create(array('type_name' => 'architect'));
		RelationType::create(array('type_name' => 'betonboorder'));
		RelationType::create(array('type_name' => 'betonstaalvlechter'));
		RelationType::create(array('type_name' => 'betontimmerman'));
		RelationType::create(array('type_name' => 'containerverhuur'));
		RelationType::create(array('type_name' => 'cv-installateur'));
		RelationType::create(array('type_name' => 'dakdekker'));
		RelationType::create(array('type_name' => 'elektricien'));
		RelationType::create(array('type_name' => 'gevelreiniger'));
		RelationType::create(array('type_name' => 'glazenwasser'));
		RelationType::create(array('type_name' => 'grondwerker'));
		RelationType::create(array('type_name' => 'ijzervlechter'));
		RelationType::create(array('type_name' => 'ingenieursbureau'));
		RelationType::create(array('type_name' => 'installateur'));
		RelationType::create(array('type_name' => 'interieurarchitect'));
		RelationType::create(array('type_name' => 'klusjesman'));
		RelationType::create(array('type_name' => 'loodgieter'));
		RelationType::create(array('type_name' => 'metselaar'));
		RelationType::create(array('type_name' => 'meubelmaker'));
		RelationType::create(array('type_name' => 'natuursteenwerker'));
		RelationType::create(array('type_name' => 'opdrachtgever'));
		RelationType::create(array('type_name' => 'overheid'));
		RelationType::create(array('type_name' => 'overig'));
		RelationType::create(array('type_name' => 'parketteur'));
		RelationType::create(array('type_name' => 'schilder'));
		RelationType::create(array('type_name' => 'schoonmaakbedrijf'));
		RelationType::create(array('type_name' => 'steigerbouwer'));
		RelationType::create(array('type_name' => 'stukadoor'));
		RelationType::create(array('type_name' => 'tegelzetter'));
		RelationType::create(array('type_name' => 'timmerman'));
		RelationType::create(array('type_name' => 'tuinman'));
		RelationType::create(array('type_name' => 'tussenpersoon'));
		RelationType::create(array('type_name' => 'vereniging van eigenaren'));
		RelationType::create(array('type_name' => 'verhuurbedrijf'));
		RelationType::create(array('type_name' => 'verwarmingsmonteur'));
		RelationType::create(array('type_name' => 'vloerenlegger'));
		RelationType::create(array('type_name' => 'voeger'));
		RelationType::create(array('type_name' => 'woningbouwvereniging'));
		RelationType::create(array('type_name' => 'zonwering'));
		$this->command->info('RelationType created');

		RelationKind::create(array('kind_name' => 'Zakelijk'));
		RelationKind::create(array('kind_name' => 'Particulier'));
		$this->command->info('RelationKind created');

		Valid::create(array('valid_name' => '5 dagen'));
		Valid::create(array('valid_name' => '14 dagen'));
		Valid::create(array('valid_name' => '30 dagen'));
		Valid::create(array('valid_name' => '2 maanden'));
		Valid::create(array('valid_name' => '3 maanden'));
		$this->command->info('Valid created');

		DeliverTime::create(array('delivertime_name' => '1 week'));
		DeliverTime::create(array('delivertime_name' => '2 weken'));
		DeliverTime::create(array('delivertime_name' => '3 weken'));
		DeliverTime::create(array('delivertime_name' => '1 maand'));
		$this->command->info('DeliverTime created');

		SystemOption::create(array('option_key' => 'tool_name', 'option_value' => 'Calctool'));
		$this->command->info('SystemOption created');

		Tax::create(array('tax_rate' => 0));
		Tax::create(array('tax_rate' => 6));
		Tax::create(array('tax_rate' => 21));
		$this->command->info('Tax created');

		TimesheetKind::create(array('kind_name' => 'aanneming'));
		TimesheetKind::create(array('kind_name' => 'stelpost'));
		TimesheetKind::create(array('kind_name' => 'meerwerk'));
		$this->command->info('TimesheetKind created');

		PurchaseKind::create(array('kind_name' => 'aanneming'));
		PurchaseKind::create(array('kind_name' => 'onderaanneming'));
		$this->command->info('PurchaseKind created');

		SystemMessage::create(array('title' => 'Let Op!', 'content' => 'Dit is een voorbeeld melding', 'active' => true));
		$this->command->info('SystemMessage created');
	}
 }
